export enum Plans {
	'Hansons Beginner' = 'Hansons Beginner - 18 weeks',
	'Hansons Advanced' = 'Hansons Advanced - 18 weeks',
	'Higdon Novice 1' = 'Higdon Novice 1 - 18 weeks',
	'Higdon Novice 2' = 'Higdon Novice 2 - 18 weeks',
	'Higdon Intermediate 1' = 'Higdon Intermediate 1 - 18 weeks',
	'Higdon Intermediate 2' = 'Higdon Intermediate 2 - 18 weeks',
	'Higdon Advanced 1' = 'Higdon Advanced 1 - 18 weeks',
	'Higdon Advanced 2' = 'Higdon Advanced 2 - 18 weeks',
	'Pfitzinger/Douglas: Up to 55 mi/wk, 18 weeks' = 'Pfitzinger/Douglas: Up to 55 mi/wk - 18 weeks',
	'Pfitzinger/Douglas: 55-70 mi/Wk, 18 weeks' = 'Pfitzinger/Douglas: 55-70 mi/Wk - 18 weeks',
	'Pfitzinger/Douglas: 70-85 mi/wk, 18 weeks' = 'Pfitzinger/Douglas: 70-85 mi/wk - 18 weeks',
	'Pfitzinger/Douglas: Up to 55 mi/wk, 12 weeks' = 'Pfitzinger/Douglas: Up to 55 mi/wk - 12 weeks',
	'Pfitzinger/Douglas: 55-70 mi/wk, 12 weeks' = 'Pfitzinger/Douglas: 55-70 mi/wk - 12 weeks',
	'Hansons Beginner Half Marathon' = 'Hansons Beginner Half Marathon - 18 weeks',
	'Hansons Advanced Half Marathon' = 'Hansons Advanced Half Marathon - 18 weeks',
	'JenReviews, 6 months' = 'JenReviews - 26 weeks',
}

export const plans = {
	'Hansons Beginner - 18 weeks': {
		length: 18,
		name: 'Hansons Beginner',
		workouts: [
			`rest`,
			`2 mi`,
			`rest`,
			`2 mi`,
			`rest`,
			`3 mi`,
			`4 mi`,
			`rest`,
			`3 mi`,
			`rest`,
			`3 mi`,
			`3 mi`,
			`3 mi`,
			`4 mi`,
			`rest`,
			`4 mi`,
			`rest`,
			`4 mi`,
			`4 mi`,
			`4 mi`,
			`5 mi`,
			`rest`,
			`5 mi`,
			`rest`,
			`3 mi`,
			`3 mi`,
			`5 mi`,
			`4 mi`,
			`rest`,
			`5 mi`,
			`rest`,
			`4 mi`,
			`5 mi`,
			`4 mi`,
			`6 mi`,
			`4 mi`,
			`1.5M warm up 12x400m @5k-10k pace w/ 400m jog rest 1.5M cool down`,
			`rest`,
			`1M warm up 5 Mile Tempo @Goal MP 1M cool down`,
			`4 mi`,
			`8 mi`,
			`8 mi`,
			`4 mi`,
			`1.5M warm up 8x600m @ 5k-10k Pace w. 400m jog rest 1.5M cool down`,
			`rest`,
			`1M warm up 5 Mile Tempo @ Goal MP 1M cool down`,
			`4 mi`,
			`6 mi`,
			`10 mi`,
			`6 mi`,
			`1.5M warm up 6x800m @ 5k-10k Pace w. 400m jog rest 1.5M cool down`,
			`rest`,
			`1M warm up 5 Mile Tempo @ Goal MP 1M cool down`,
			`5 mi`,
			`6 mi`,
			`10 mi`,
			`5 mi`,
			`1.5M warm up 5x1km @ 5k-10k Pace w. 400m jog rest 1.5M cool down`,
			`rest`,
			`1M warm up 8 Mile Tempo @ Goal MP 1M cool down`,
			`6 mi`,
			`5 mi`,
			`15 mi`,
			`7 mi`,
			`1.5M warm up 4x1200m @ 5k-10k Pace w. 400m jog rest 1.5M cool down`,
			`rest`,
			`1M warm up 8 Mile Tempo @ Goal MP 1M cool down`,
			`5 mi`,
			`8 mi`,
			`10 mi`,
			`5 mi`,
			`1.5M warm up 6xMile @MP-10s w. 400m jog rest 1.5M cool down`,
			`rest`,
			`1M warm up 8 Mile Tempo @ Goal MP 1M cool down`,
			`6 mi`,
			`8 mi`,
			`16 mi`,
			`5 mi`,
			`1.5M warm up 4x1.5 Miles @MP-10s w. 800m jog rest 1.5M cool down`,
			`rest`,
			`1M warm up 9 Mile Tempo @ Goal MP 1M cool down`,
			`5 mi`,
			`8 mi`,
			`10 mi`,
			`7 mi`,
			`1.5M warm up 3x2 Miles @MP-10s w. 800m jog rest 1.5M cool down`,
			`rest`,
			`1M warm up 9 Mile Tempo @ Goal MP 1M cool down`,
			`6 mi`,
			`6 mi`,
			`16 mi`,
			`5 mi`,
			`1.5M warm up 2x3 Miles @MP-10s w. 1 Mi jog rest 1.5M cool down`,
			`rest`,
			`1M warm up 9 Mile Tempo @ Goal MP 1M cool down`,
			`5 mi`,
			`8 mi`,
			`10 mi`,
			`7 mi`,
			`1.5M warm up 3x2 Miles @MP-10s w.800m jog rest 1.5M cool down`,
			`rest`,
			`1M warm up 10 Mile Tempo @ Goal MP 1M cool down`,
			`6 mi`,
			`6 mi`,
			`16 mi`,
			`5 mi`,
			`1.5M warm up 4x1.5 Miles @MP-10s w.800m jog rest 1.5M cool down`,
			`rest`,
			`1M warm up 10 Mile Tempo @ Goal MP 1M cool down`,
			`5 mi`,
			`8 mi`,
			`10 mi`,
			`7 mi`,
			`1.5M warm up 6xMile @MP-10s w.400m jog rest 1.5M cool down`,
			`rest`,
			`1M warm up 10 Mile Tempo @ Goal MP 1M cool down`,
			`6 mi`,
			`6 mi`,
			`8 mi`,
			`5 mi`,
			`5 mi`,
			`rest`,
			`6 mi`,
			`5 mi`,
			`3 mi`,
			`race`,
		],
	},
	'Hansons Advanced - 18 weeks': {
		length: 18,
		name: 'Hansons Advanced',
		workouts: [
			'6mi easy',
			'6mi easy',
			'rest or cross-train',
			'6mi easy',
			'6mi easy',
			'6mi easy',
			'8mi easy',
			'6mi easy',
			'2mi warm up 12x400m @ 5k-10k Pace w. 400m jog rest 2mi cool down',
			'rest or cross-train',
			'6mi easy',
			'6mi easy',
			'6mi easy',
			'8mi easy',
			'6mi easy',
			'2mi warm up 8x600m @ 5k-10k Pace w. 400m jog rest 2mi cool down',
			'Rest or cross-train',
			'1mi warm up 6mi Tempo @ Goal MP 1mi cool down',
			'7mi easy',
			'6mi easy',
			'10mi long run',
			'6mi easy',
			'2mi warm up 6x800m @ 5k-10k Pace w. 400m jog rest 2mi cool down',
			'Rest or cross-train',
			'1mi warm up 6mi Tempo @ Goal MP 1mi cool down',
			'6mi easy',
			'8mi easy',
			'10mi long run',
			'6mi easy',
			'2mi warm up 5x1km @ 5k-10k Pace w. 400m jog rest 2mi cool down',
			'Rest or cross-train',
			'1mi warm up 6mi Tempo @ Goal MP 1mi cool down',
			'7mi easy',
			'8mi easy',
			'12mi long run',
			'6mi easy',
			'2mi warm up 4x1200m @ 5k-10k Pace w. 400m jog rest 2mi cool down',
			'Rest or cross-train',
			'1mi warm up 7mi Tempo @ Goal MP 1mi cool down',
			'6mi easy',
			'8mi easy',
			'10mi easy',
			'6mi easy',
			'2mi warm up 3x1mi @ 5k-10k Pace w. 800m jog rest 2mi cool down',
			'Rest or cross-train',
			'1mi warm up 7mi Tempo @ Goal MP 1mi cool down',
			'7mi easy',
			'8mi easy',
			'14mi long run',
			'6mi easy',
			'2mi warm up 4x1200m @ 5k-10k Pace w. 400m jog rest 2mi cool down',
			'Rest or cross-train',
			'1mi warm up 7mi Tempo @ Goal MP 1mi cool down',
			'6mi easy',
			'10mi easy',
			'10mi long run',
			'8mi easy',
			'2mi warm up 5x1km @ 5k-10k Pace w. 400m jog rest 2mi cool down',
			'Rest or cross-train',
			'1mi warm up 8mi Tempo @ Goal MP 1mi cool down',
			'7mi easy',
			'8mi easy',
			'15mi long run',
			'6mi easy',
			'2mi warm up 6x800m @ 5k-10k Pace w. 400m jog rest 2mi cool down',
			'Rest or cross-train',
			'1mi warm up 8mi Tempo @ Goal MP 1mi cool down',
			'6mi easy',
			'10mi easy',
			'10mi long run',
			'8mi easy',
			'2mi warm up 6x1mi @ MP - 10s w. 400m jog rest 2mi cool down',
			'Rest or cross-train',
			'1mi warm up 8mi Tempo @ Goal MP 1mi cool down',
			'7mi easy',
			'8mi easy',
			'16mi long run',
			'6mi easy',
			'2mi warm up 4x2mi @ MP - 10s w. 800m jog rest 2mi cool down',
			'Rest or cross-train',
			'1mi warm up 9mi Tempo @ Goal MP 1mi cool down',
			'6mi easy',
			'10mi easy',
			'10mi long run',
			'8mi easy',
			'2mi warm up 3x2mi @ MP - 10s w. 800m jog rest 2mi cool down',
			'Rest or cross-train',
			'1mi warm up 9mi Tempo @ Goal MP 1mi cool down',
			'7mi easy',
			'8mi easy',
			'16mi long run',
			'6mi easy',
			'2mi warm up 2x3mi @ MP - 10s w. 1mi jog rest 2mi cool down',
			'Rest or cross-train',
			'1mi warm up 9mi Tempo @ Goal MP 1mi cool down',
			'6mi easy',
			'10mi easy',
			'10mi long run',
			'8mi easy',
			'2mi warm up 3x2mi @ MP - 10s w. 800m jog rest 2mi cool down',
			'Rest or cross-train',
			'1mi warm up 10mi Tempo @ Goal MP 1mi cool down',
			'7mi easy',
			'8mi easy',
			'16mi long run',
			'6mi easy',
			'2mi warm up 4x2mi @ MP - 10s w. 800m jog rest 2mi cool down',
			'Rest or cross-train',
			'1mi warm up 10mi Tempo @ Goal MP 1mi cool down',
			'6mi easy',
			'10mi easy',
			'10 long run',
			'8mi easy',
			'2mi warm up 6x1mi @ MP - 10s w. 400m jog rest 2mi cool down',
			'Rest or cross-train',
			'1mi warm up 10mi Tempo @ Goal MP 1mi cool down',
			'7mi easy',
			'8mi easy',
			'8mi easy',
			'6mi easy',
			'5mi easy',
			'Rest',
			'6mi easy',
			'6mi easy',
			'3mi easy',
			'Race Day!',
		],
	},
	'Higdon Novice 1 - 18 weeks': {
		length: 18,
		name: 'Higdon Novice 1',
		workouts: [
			'rest',
			'3 mi',
			'3 mi',
			'3 mi',
			'rest',
			'6 mi',
			'cross',
			'rest',
			'3 mi',
			'3 mi',
			'3 mi',
			'rest',
			'7 mi',
			'cross',
			'rest',
			'3 mi',
			'4 mi',
			'3 mi',
			'rest',
			'5 mi',
			'cross',
			'rest',
			'3 mi',
			'4 mi',
			'3 mi',
			'rest',
			'9 mi',
			'cross',
			'rest',
			'3 mi',
			'5 mi',
			'3 mi',
			'rest',
			'10 mi',
			'cross',
			'rest',
			'3 mi',
			'5 mi',
			'3 mi',
			'rest',
			'7 mi',
			'cross',
			'rest',
			'3 mi',
			'6 mi',
			'3 mi',
			'rest',
			'12 mi',
			'cross',
			'rest',
			'3 mi',
			'6 mi',
			'3 mi',
			'rest',
			'rest',
			'Half Marathon',
			'rest',
			'3 mi',
			'7 mi',
			'4 mi',
			'rest',
			'10 mi',
			'cross',
			'rest',
			'3 mi',
			'7 mi',
			'4 mi',
			'rest',
			'15 mi',
			'cross',
			'rest',
			'4 mi',
			'8 mi',
			'4 mi',
			'rest',
			'16 mi',
			'cross',
			'rest',
			'4 mi',
			'8 mi',
			'5 mi',
			'rest',
			'12 mi',
			'cross',
			'rest',
			'4 mi',
			'9 mi',
			'5 mi',
			'rest',
			'18 mi',
			'cross',
			'rest',
			'5 mi',
			'9 mi',
			'5 mi',
			'rest',
			'14 mi',
			'cross',
			'rest',
			'5 mi',
			'10 mi',
			'5 mi',
			'rest',
			'20 mi',
			'cross',
			'rest',
			'5 mi',
			'8 mi',
			'4 mi',
			'rest',
			'12 mi',
			'cross',
			'rest',
			'4 mi',
			'6 mi',
			'3 mi',
			'rest',
			'8 mi',
			'cross',
			'rest',
			'3 mi',
			'4 mi',
			'2 mi',
			'rest',
			'rest',
			'Marathon',
		],
	},
	'Higdon Novice 2 - 18 weeks': {
		length: 18,
		name: 'Higdon Novice 2',
		workouts: [
			'Rest',
			'3mi run',
			'5mi pace',
			'3mi run',
			'Rest',
			'8mi',
			'Cross',
			'Rest',
			'3mi run',
			'5mi run',
			'3mi run',
			'Rest',
			'9mi',
			'Cross',
			'Rest',
			'3mi run',
			'5mi pace',
			'3mi run',
			'Rest',
			'6mi',
			'Cross',
			'Rest',
			'3mi run',
			'6mi pace',
			'3mi run',
			'Rest',
			'11mi',
			'Cross',
			'Rest',
			'3mi run',
			'6mi run',
			'3mi run',
			'Rest',
			'12mi',
			'Cross',
			'Rest',
			'3mi run',
			'6mi pace',
			'3mi run',
			'Rest',
			'9mi',
			'Cross',
			'Rest',
			'4mi run',
			'7mi pace',
			'4mi run',
			'Rest',
			'14mi',
			'Cross',
			'Rest',
			'4mi run',
			'7mi run',
			'4mi run',
			'Rest',
			'15mi',
			'Cross',
			'Rest',
			'4mi run',
			'7mi pace',
			'4mi run',
			'Rest',
			'Rest',
			'13.1mi Half Marathon',
			'Rest',
			'4mi run',
			'8mi pace',
			'4mi run',
			'Rest',
			'17mi',
			'Cross',
			'Rest',
			'5mi run',
			'8mi run',
			'5mi run',
			'Rest',
			'18mi',
			'Cross',
			'Rest',
			'5mi run',
			'8mi pace',
			'5mi run',
			'Rest',
			'13mi',
			'Cross',
			'Rest',
			'5mi run',
			'5mi pace',
			'5mi run',
			'Rest',
			'19mi',
			'Cross',
			'Rest',
			'5mi run',
			'8mi run',
			'5mi run',
			'Rest',
			'12mi',
			'Cross',
			'Rest',
			'5mi run',
			'5mi pace',
			'5mi run',
			'Rest',
			'20mi',
			'Cross',
			'Rest',
			'5mi run',
			'4mi pace',
			'5mi run',
			'Rest',
			'12mi',
			'Cross',
			'Rest',
			'4mi run',
			'3mi run',
			'4mi run',
			'Rest',
			'8mi',
			'Cross',
			'Rest',
			'3mi run',
			'2mi run',
			'Rest',
			'Rest',
			'2mi run',
			'Marathon',
		],
	},
	'Higdon Intermediate 1 - 18 weeks': {
		length: 18,
		name: 'Higdon Intermediate 1',
		workouts: [
			'Cross',
			'3mi run',
			'5mi run',
			'3mi run',
			'Rest',
			'5mi pace',
			'8mi',
			'Cross',
			'3mi run',
			'5mi run',
			'3mi run',
			'Rest',
			'5mi run',
			'9mi',
			'Cross',
			'3mi run',
			'5mi run',
			'3mi run',
			'Rest',
			'5mi pace',
			'6mi',
			'Cross',
			'3mi run',
			'6mi run',
			'3mi run',
			'Rest',
			'6mi pace',
			'11mi',
			'Cross',
			'3mi run',
			'6mi run',
			'3mi run',
			'Rest',
			'6mi run',
			'12mi',
			'Cross',
			'3mi run',
			'5mi run',
			'3mi run',
			'Rest',
			'6mi pace',
			'9mi',
			'Cross',
			'4mi run',
			'7mi run',
			'4mi run',
			'Rest',
			'7mi pace',
			'14mi',
			'Cross',
			'4mi run',
			'7mi run',
			'4mi run',
			'Rest',
			'7mi run',
			'15mi',
			'Cross',
			'4mi run',
			'5mi run',
			'4mi run',
			'Rest',
			'Rest',
			'13.1mi Half Marathon',
			'Cross',
			'4mi run',
			'8mi run',
			'4mi run',
			'Rest',
			'8mi pace',
			'17mi',
			'Cross',
			'5mi run',
			'8mi run',
			'5mi run',
			'Rest',
			'8mi run',
			'18mi',
			'Cross',
			'5mi run',
			'5mi run',
			'5mi run',
			'Rest',
			'8mi pace',
			'13mi',
			'Cross',
			'5mi run',
			'8mi run',
			'5mi run',
			'Rest',
			'5mi pace',
			'20mi',
			'Cross',
			'5mi run',
			'5mi run',
			'5mi run',
			'Rest',
			'8mi run',
			'12mi',
			'Cross',
			'5mi run',
			'8mi run',
			'5mi run',
			'Rest',
			'5mi pace',
			'20mi',
			'Cross',
			'5mi run',
			'6mi run',
			'5mi run',
			'Rest',
			'4mi pace',
			'12mi',
			'Cross',
			'4mi run',
			'5mi run',
			'4mi run',
			'Rest',
			'3mi run',
			'8mi',
			'Cross',
			'3mi run',
			'4mi run',
			'Rest',
			'Rest',
			'2mi run',
			'Marathon',
		],
	},
	'Higdon Intermediate 2 - 18 weeks': {
		length: 18,
		name: 'Higdon Intermediate 2',
		workouts: [
			'Cross',
			'3mi run',
			'5mi run',
			'3mi run',
			'Rest',
			'5mi pace',
			'10mi',
			'Cross',
			'3mi run',
			'5mi run',
			'3mi run',
			'Rest',
			'5mi run',
			'11mi',
			'Cross',
			'3mi run',
			'6mi run',
			'3mi run',
			'Rest',
			'6mi pace',
			'8mi',
			'Cross',
			'3mi run',
			'6mi run',
			'3mi run',
			'Rest',
			'6mi pace',
			'13mi',
			'Cross',
			'3mi run',
			'7mi run',
			'3mi run',
			'Rest',
			'7mi run',
			'14mi',
			'Cross',
			'3mi run',
			'7mi run',
			'3mi run',
			'Rest',
			'7mi pace',
			'10mi',
			'Cross',
			'4mi run',
			'8mi run',
			'4mi run',
			'Rest',
			'8mi pace',
			'16mi',
			'Cross',
			'4mi run',
			'8mi run',
			'4mi run',
			'Rest',
			'8mi run',
			'17mi',
			'Cross',
			'4mi run',
			'9mi run',
			'4mi run',
			'Rest',
			'Rest',
			'13.1mi Half Marathon',
			'Cross',
			'4mi run',
			'9mi run',
			'4mi run',
			'Rest',
			'9mi pace',
			'19mi',
			'Cross',
			'5mi run',
			'10mi run',
			'5mi run',
			'Rest',
			'10mi run',
			'20mi',
			'Cross',
			'5mi run',
			'6mi run',
			'5mi run',
			'Rest',
			'6mi pace',
			'12mi',
			'Cross',
			'5mi run',
			'10mi run',
			'5mi run',
			'Rest',
			'10mi pace',
			'20mi',
			'Cross',
			'5mi run',
			'6mi run',
			'5mi run',
			'Rest',
			'6mi run',
			'12mi',
			'Cross',
			'5mi run',
			'10mi run',
			'5mi run',
			'Rest',
			'10mi pace',
			'20mi',
			'Cross',
			'5mi run',
			'8mi run',
			'5mi run',
			'Rest',
			'4mi pace',
			'12mi',
			'Cross',
			'4mi run',
			'6mi run',
			'4mi run',
			'Rest',
			'4mi run',
			'8mi',
			'Cross',
			'3mi run',
			'4mi run',
			'Rest',
			'Rest',
			'2mi run',
			'Marathon',
		],
	},
	'Higdon Advanced 1 - 18 weeks': {
		length: 18,
		name: 'Higdon Advanced 1',
		workouts: [
			'3mi run',
			'5mi run',
			'3mi run',
			'3xhill',
			'Rest',
			'5mi pace',
			'10mi',
			'3mi run',
			'5mi run',
			'3mi run',
			'30 tempo',
			'Rest',
			'5mi pace',
			'11mi',
			'3mi run',
			'6mi run',
			'3mi run',
			'4x800',
			'Rest',
			'6mi pace',
			'8mi',
			'3mi run',
			'6mi run',
			'3mi run',
			'4xhill',
			'Rest',
			'6mi pace',
			'13mi',
			'3mi run',
			'7mi run',
			'3mi run',
			'35 tempo',
			'Rest',
			'7mi run',
			'14mi',
			'3mi run',
			'7mi run',
			'3mi run',
			'5x800',
			'Rest',
			'7mi pace',
			'10mi',
			'3mi run',
			'8mi run',
			'4mi run',
			'5xhill',
			'Rest',
			'8mi pace',
			'16mi',
			'3mi run',
			'8mi run',
			'4mi run',
			'40 tempo',
			'Rest',
			'8mi run',
			'17mi',
			'3mi run',
			'9mi run',
			'4mi run',
			'6x800',
			'Rest',
			'Rest',
			'Half Marathon',
			'3mi run',
			'9mi run',
			'4mi run',
			'6xhill',
			'Rest',
			'9mi pace',
			'19mi',
			'4mi run',
			'10mi run',
			'5mi run',
			'45 tempo',
			'Rest',
			'10mi pace',
			'20mi',
			'4mi run',
			'6mi run',
			'5mi run',
			'7x800',
			'Rest',
			'6mi pace',
			'12mi',
			'4mi run',
			'10mi run',
			'5mi run',
			'7xhill',
			'Rest',
			'10mi pace',
			'20mi',
			'5mi run',
			'6mi run',
			'5mi run',
			'45 tempo',
			'Rest',
			'6mi run',
			'12mi',
			'5mi run',
			'10mi run',
			'5mi run',
			'8x800',
			'Rest',
			'10mi run',
			'20mi',
			'5mi run',
			'8mi run',
			'5mi run',
			'6xhill',
			'Rest',
			'4mi pace',
			'12mi',
			'4mi run',
			'6mi run',
			'4mi run',
			'30 tempo',
			'Rest',
			'4mi run',
			'8mi',
			'3mi run',
			'4x400',
			'2mi run',
			'Rest',
			'Rest',
			'2mi run',
			'Marathon',
		],
	},
	'Higdon Advanced 2 - 18 weeks': {
		length: 18,
		name: 'Higdon Advanced 2',
		workouts: [
			'3mi run',
			'3xhill',
			'3mi run',
			'30 tempo',
			'Rest',
			'5mi pace',
			'10mi',
			'3mi run',
			'30 tempo',
			'3mi run',
			'3mi pace',
			'Rest',
			'5mi run',
			'11mi',
			'3mi run',
			'4x800',
			'3mi run',
			'30 tempo',
			'Rest',
			'6mi pace',
			'8mi',
			'3mi run',
			'4xhill',
			'3mi run',
			'30 tempo',
			'Rest',
			'6mi pace',
			'13mi',
			'3mi run',
			'35 tempo',
			'3mi run',
			'3mi pace',
			'Rest',
			'7mi run',
			'14mi',
			'3mi run',
			'5x800',
			'3mi run',
			'35 tempo',
			'Rest',
			'7mi pace',
			'10mi',
			'3mi run',
			'5xhill',
			'4mi run',
			'40 tempo',
			'Rest',
			'8mi pace',
			'16mi',
			'3mi run',
			'40 tempo',
			'4mi run',
			'3mi pace',
			'Rest',
			'8mi run',
			'17mi',
			'4mi run',
			'6x800',
			'4mi run',
			'40 tempo',
			'Rest',
			'Rest',
			'Half Marathon',
			'3mi run',
			'6xhill',
			'4mi run',
			'45 tempo',
			'Rest',
			'9mi pace',
			'19mi',
			'4mi run',
			'45 tempo',
			'5mi run',
			'4mi pace',
			'Rest',
			'10mi run',
			'20mi',
			'4mi run',
			'7x800',
			'5mi run',
			'45 tempo',
			'Rest',
			'6mi pace',
			'12mi',
			'4mi run',
			'7xhill',
			'5mi run',
			'50 tempo',
			'Rest',
			'10mi pace',
			'20mi',
			'5mi run',
			'45 tempo',
			'5mi run',
			'5mi pace',
			'Rest',
			'6mi run',
			'12mi',
			'5mi run',
			'8x800',
			'5mi run',
			'40 tempo',
			'Rest',
			'10mi pace',
			'20mi',
			'5mi run',
			'6xhill',
			'5mi run',
			'30 tempo',
			'Rest',
			'4mi pace',
			'12mi',
			'4mi run',
			'30 tempo',
			'4mi run',
			'4mi pace',
			'Rest',
			'4mi run',
			'8mi',
			'3mi run',
			'4x400',
			'3mi run',
			'Rest',
			'Rest',
			'2mi run',
			'Marathon',
		],
	},
	'Pfitzinger/Douglas: Up to 55 mi/wk - 18 weeks': {
		length: 18,
		name: 'Pfitzinger/Douglas: Up to 55 mi/wk, 18 weeks',
		workouts: [
			'Rest or cross-train',
			'Lactate threshold 8mi w 4mi @15K to half marathon pace',
			'Rest or cross-train',
			'General aerobic 9mi',
			'Rest or cross-train',
			'Recovery 4mi',
			'Medium - long run 12mi',
			'Rest or cross-train',
			'General aerobic + speed 8mi w / 10x100m strides',
			'Rest or cross-train',
			'General aerobic 10mi',
			'Rest or cross-train',
			'Recovery 5mi',
			'Marathon pace run 13mi w / 8mi @marathon race pace',
			'Rest or cross-train',
			'General aerobic 10mi',
			'Recovery 4mi',
			'Lactate threshold 8mi w 4mi @15K to half marathon race pace',
			'Rest or cross-train',
			'Recovery 4mi',
			'Medium - long run 14mi',
			'Rest or cross-train',
			'General aerobic + speed 8mi w / 10X100 m strides',
			'Recovery 5mi',
			'General aerobic 10mi',
			'Rest or cross-train',
			'Recovery 4mi',
			'Medium - long run 15mi',
			'Rest or cross-train',
			'Lactate threshold 9mi w 5mi @15K to half marathon race pace',
			'Recovery 5mi',
			'General aerobic 10mi',
			'Rest or cross-train',
			'Recovery 5mi',
			'Marathon pace run 16mi w 10mi @marathon race pace',
			'Rest or cross-train',
			'General aerobic + speed 8mi w / 10x100m strides',
			'Recovery 5mi',
			'General aerobic 8mi',
			'Rest or cross-train',
			'Recovery 4mi',
			'Medium - long run 12mi',
			'Rest or cross-train',
			'Lactate threshold 10mi w 5mi @15K to half marathon race pace',
			'Recovery 4mi',
			'Medium - long run 11mi',
			'Rest or cross-train',
			'General aerobic + speed 7mi w / 8x100m strides',
			'Long run 18 mi(34 km)',
			'Rest or cross-train',
			'Recovery + speed 7mi w / 6x100 m strides',
			'Medium - long run 12mi',
			'Rest or cross-train',
			'Lactate threshold 10mi w / 6mi @15K to half marathon race pace',
			'Recovery 5mi',
			'Long run 20mi',
			'Rest or cross-train',
			'Recovery 6mi',
			'Medium - long run 14mi',
			'Recovery 6mi',
			'Rest or cross-train',
			'Recovery + speed 6mi w / 6x100 m strides',
			'Marathon - pace run 16mi w / 12mi @marathon race pace',
			'Rest or cross-train',
			'General aerobic 8mi',
			'VO₂ Max 8mi w / 5x800 m @5K race pace; jog 50 to 90 % interval time between',
			'Recovery 5mi',
			'Rest or cross-train',
			'General aerobic + speed 8mi w / 8x100m strides',
			'Medium - long run 14mi',
			'Rest or cross-train',
			'Recovery + speed 7mi w / 6x100 m strides',
			'Lactate threshold 11mi w / 7mi @15K to half marathon race pace',
			'Rest or cross-train',
			'Medium - long run 12mi',
			'Recovery 5mi',
			'Long run 20mi',
			'Rest or cross-train',
			'VO₂ Max 8mi w / 5x600 m @5K race pace; jog 50 to 90 % interval time between',
			'Medium - long run 12mi',
			'Rest or cross-train',
			'Recovery + speed 5mi w / 6x100 m strides',
			'8K - 15K tune - up race(total 9 - 13 mi / 14 - 21 km)',
			'Long run 17mi',
			'Rest or cross-train',
			'General aerobic 8mi',
			'VO₂ Max 9mi w / 5x1, 000 m @5K race pace; jog 50 to 90 % interval time between',
			'Rest or cross-train',
			'Medium - long run 12mi',
			'Recovery 5mi',
			'Marathon - pace run 18mi w / 14mi @marathon race pace',
			'Rest or cross-train',
			'VO₂ Max 8mi w / 5x600 m @5K race pace; jog 50 to 90 % interval time between',
			'Medium - long run 11mi',
			'Rest or cross-train',
			'Recovery + speed 4mi w / 6x100 m strides',
			'8K - 15K tune - up race(total 9 - 13 mi / 14 - 21 km)',
			'Long run 17mi',
			'Rest or cross-train',
			'Recovery + speed 7mi w / 6x100 m strides',
			'VO₂ Max 10mi w / 4x1, 200 m @5K race pace; jog 50 to 90 % interval time between',
			'Rest or cross-train',
			'Medium - long run 11mi',
			'Recovery 4mi',
			'Long run 20mi',
			'Rest or cross-train',
			'VO₂ Max 8mi w / 5x600 m @5K race pace; jog 50 to 90 % interval time between',
			'Recovery 6mi',
			'Rest or cross-train',
			'Recovery + speed 4mi w / 6x100 m strides',
			'8K - 10K tune - up race(total 9 - 11 mi / 14 - 18 km)',
			'Long run 16mi',
			'Rest or cross-train',
			'General aerobic + speed 7mi w / 8x100m strides',
			'VO₂ Max 8mi w / 3x1, 600 m @5K race pace; jog 50 to 90 % interval time between',
			'Rest or cross-train',
			'Recovery + speed 5mi w / 6x100 m strides',
			'Rest or cross-train',
			'Medium - long run 12mi',
			'Rest',
			'Recovery 6mi',
			'Dress rehearsal 7mi w / 2mi @marathon race pace',
			'Rest',
			'Recovery + speed 5mi w / 6x100 m strides',
			'Recovery 4mi',
			'Goal marathon 26.2mi',
		],
	},
	'Pfitzinger/Douglas: 55-70 mi/Wk - 18 weeks': {
		length: 18,
		name: 'Pfitzinger/Douglas: 55-70 mi/Wk, 18 weeks',
		workouts: [
			'Rest or cross-train',
			'Lactate threshold 9mi w 2mi @15K to half marathon pace',
			'Medium - long run 11mi',
			'Recovery 5mi',
			'General aerobic 9mi',
			'Recovery 5mi',
			'Medium - long run 15mi',
			'Rest or cross-train',
			'General aerobic + speed 8mi w / 10x100m strides',
			'Medium - long run 12mi',
			'Recovery 5mi',
			'General aerobic 9mi',
			'Recovery 5mi',
			'Marathon pace run 17mi w / 8mi @marathon race pace',
			'Rest or cross-train',
			'Medium - long run 11mi',
			'Medium - long run 13mi',
			'Recovery 5mi',
			'Lactate threshold 9mi w 4mi @15K to half marathon race pace',
			'Recovery 5mi',
			'Medium - long run 15mi',
			'Rest or cross-train',
			'General aerobic + speed 9mi w / 10X100 m strides',
			'Medium - long run 14mi',
			'Recovery 5mi',
			'Medium - long run 11mi',
			'Recovery 5mi',
			'Long run 18mi',
			'Rest or cross-train',
			'Lactate threshold 9mi w 5mi @15K to half marathon race pace',
			'Medium - long run 14mi',
			'Recovery 5mi',
			'Medium - long run 12mi',
			'Recovery 5mi',
			'Marathon pace run 18mi w 10mi @marathon race pace',
			'Rest or cross-train',
			'General aerobic + speed 8mi w / 10x100m strides',
			'Medium - long run 12mi',
			'Recovery 5mi',
			'General aerobic 10mi',
			'Recovery 5mi',
			'Medium - long run 15mi',
			'Rest or cross-train',
			'Lactate threshold 10mi w 5mi @15K to half marathon race pace',
			'Medium - long run 14mi',
			'Recovery 5mi',
			'Medium - long run 11mi',
			'General aerobic + speed 7mi w / 10x100m strides',
			'Long run 21 mi(34 km)',
			'Rest or cross-train',
			'Recovery 6mi a.m. 4mi p.m.',
			'Medium - long run 14mi',
			'Recovery 5mi',
			'Lactate threshold 11mi w / 6mi @15K to half marathon race pace',
			'Recovery 6mi',
			'Long run 20mi',
			'Rest or cross-train',
			'Recovery 6mi a.m. 4mi p.m.',
			'Medium - long run 15mi',
			'Recovery 6mi',
			'Medium - long run 13mi',
			'Recovery + speed 7mi w / 6x100 m strides',
			'Marathon - pace run 16mi w / 12mi @marathon race pace',
			'Rest or cross-train',
			'General aerobic 9mi',
			'VO₂ Max 9mi w / 6x800 m @5K race pace; jog 50 to 90 % interval time between',
			'Recovery 6mi',
			'Medium - long run 11mi',
			'General aerobic + speed 8mi w / 10x100m strides',
			'Medium - long run 15mi',
			'Rest or cross-train',
			'Recovery 6mi a.m. 4mi p.m.',
			'Medium - long run 15mi',
			'Recovery 6mi',
			'Lactate threshold 12mi w / 7mi @15K to half marathon race pace',
			'Recovery 5mi',
			'Long run 22mi',
			'Rest or cross-train',
			'VO₂ Max 9mi w / 5x600 m @5K race pace; jog 50 to 90 % interval time between',
			'Medium - long run 14mi',
			'Recovery + speed 6mi w / 6x100 m strides a.m. 4mi p.m.',
			'Recovery 5mi',
			'8K - 15K tune - up race(total 9 - 13 mi / 14 - 21 km)',
			'Long run 18mi',
			'Rest or cross-train',
			'VO₂ Max 10mi w / 6x1, 000 m @5K race pace; jog 50 to 90 % interval time between',
			'Medium - long run 15mi',
			'Recovery 6mi a.m. 4mi p.m.',
			'Medium - long run 12mi',
			'Recovery 5mi',
			'Marathon - pace run 18mi w / 14mi @marathon race pace',
			'Rest or cross-train',
			'VO₂ Max 9mi w / 5x600 m @5K race pace; jog 50 to 90 % interval time between',
			'Medium - long run 14mi',
			'Recovery + speed 6mi w / 6x100 m strides',
			'Recovery 5mi',
			'8K - 15K tune - up race(total 9 - 13 mi / 14 - 21 km)',
			'Long run 17mi',
			'Rest or cross-train',
			'Recovery 6mi a.m. 4mi p.m.',
			'VO₂ Max 11mi w / 5x1, 200 m @5K race pace; jog 50 to 90 % interval time between',
			'Medium - long run 14mi',
			'General aerobic + speed 8mi w / 8x100 m strides',
			'Recovery 5mi',
			'Long run 20mi',
			'Rest or cross-train',
			'Recovery + speed 7mi w / 8x100 m strides',
			'Medium - long run 12mi',
			'Recovery + speed 5mi w / 6x100 m strides',
			'Recovery 5mi',
			'8K - 10K tune - up race(total 9 - 11 mi / 14 - 18 km)',
			'Long run 17mi',
			'Rest',
			'General aerobic + speed 7mi w / 8x100 m strides',
			'Recovery 4mi',
			'VO₂ Max 8mi w / 3x1, 600 m @5K race pace; jog 50 to 90 % interval time between',
			'Recovery 5mi',
			'Recovery + speed 6mi w / 8x100 m strides',
			'Medium - long run 13mi',
			'Rest',
			'Recovery 7mi',
			'Dress rehearsal 7mi w / 2mi @marathon race pace',
			'Recovery 5mi',
			'Recovery + speed 5mi w / 6x100 m strides',
			'Recovery 4mi',
			'Goal marathon 26.2mi',
		],
	},
	'Pfitzinger/Douglas: 70-85 mi/wk - 18 weeks': {
		length: 18,
		name: 'Pfitzinger/Douglas: 70-85 mi/wk, 18 weeks',
		workouts: [
			'Recovery 5mi',
			'Lactate threshold 9mi w 4mi @15K to half marathon pace',
			'Medium - long run 12mi',
			'Recovery 6mi',
			'General aerobic 10mi',
			'Recovery 6mi',
			'Long run 17mi',
			'Recovery 6mi',
			'General aerobic + speed 8mi w / 10x100m strides',
			'Medium - long run 13mi',
			'Recovery 6mi',
			'Medium - long run 11mi',
			'Recovery 6mi',
			'Marathon pace run 17mi w / 8mi @marathon race pace',
			'Recovery 6mi',
			'Lactate threshold 10mi w 5mi @15K to half marathon race pace',
			'Medium - long run 14mi',
			'Recovery 6mi',
			'Medium - long run 12mi',
			'Recovery 6mi',
			'Medium - long run 16mi',
			'Recovery 6mi',
			'General aerobic + speed 10mi w / 10X100 m strides',
			'Medium - long run 14mi',
			'Recovery 6mi',
			'Medium - long run 12mi',
			'Recovery 6mi',
			'Long run 20mi',
			'Recovery 6mi a.m. 4mi p.m.',
			'Lactate threshold 10mi w 4mi @15K to half marathon race pace',
			'Medium - long run 15mi',
			'Recovery 6mi',
			'Medium - long run 13mi',
			'Recovery 6mi',
			'Marathon pace run 18mi w 10mi @marathon race pace',
			'Recovery 7mi',
			'General aerobic + speed 10mi w / 10x100m strides',
			'Medium - long run 13mi',
			'Recovery 6mi',
			'General aerobic 10mi',
			'Recovery 6mi',
			'Long run 16mi',
			'Recovery 6mi a.m. 4mi p.m.',
			'Lactate threshold 11mi w 5mi @15K to half marathon race pace',
			'Medium - long run 15mi',
			'Recovery 7mi',
			'Medium - long run 13mi',
			'General aerobic + speed 8mi w / 10x100m strides',
			'Long run 20 mi(34 km)',
			'Recovery 6mi a.m. 4mi p.m.',
			'General aerobic 9mi',
			'Medium - long run 15mi',
			'Recovery 7mi',
			'Lactate threshold 12mi w / 6mi @15K to half marathon race pace',
			'Recovery 7mi',
			'Long run 22mi',
			'Recovery 6mi a.m. 4mi p.m.',
			'General aerobic 9mi',
			'Medium - long run 15mi',
			'Recovery 8mi',
			'Medium - long run 13mi',
			'Recovery + speed 7mi w / 6x100 m strides',
			'Marathon - pace run 18mi w / 12mi @marathon race pace',
			'Recovery 6mi a.m. 4mi p.m.',
			'General aerobic 9mi',
			'VO₂ Max 9mi w / 6x800 m @5K race pace; jog 50 to 90 % interval time between',
			'Recovery 7mi',
			'Medium - long run 11mi a.m.Recovery 4mi p.m.',
			'General aerobic + speed 8mi w / 10x100m strides',
			'Long run 16mi',
			'Recovery 6mi a.m. 4mi p.m.',
			'General aerobic 8mi',
			'Medium - long run 15mi',
			'Recovery 6mi a.m. 4mi p.m.',
			'Lactate threshold 12mi w / 7mi @15K to half marathon race pace',
			'General aerobic 8mi',
			'Long run 24mi',
			'Recovery 6mi a.m. 4mi p.m.',
			'VO₂ Max 9mi w / 5x600 m @5K race pace; jog 50 to 90 % interval time between',
			'Medium - long run 15mi',
			'Recovery + speed 7mi w / 6x100 m strides',
			'Recovery 6mi',
			'8K - 15K tune - up race(total 9 - 13 mi / 14 - 21 km)',
			'Long run 18mi',
			'Recovery 6mi a.m. 4mi p.m.',
			'VO₂ Max 12mi w / 6x1, 000 m @5K race pace; jog 50 to 90 % interval time between',
			'Medium - long run 15mi',
			'Recovery 6mi a.m. 4mi p.m.',
			'Medium - long run 12mi',
			'Recovery 7mi',
			'Marathon - pace run 20mi w / 14mi @marathon race pace',
			'Recovery 6mi a.m. 4mi p.m.',
			'VO₂ Max 9mi w / 5x600 m @5K race pace; jog 50 to 90 % interval time between',
			'Medium - long run 14mi',
			'Recovery + speed 7mi w / 6x100 m strides',
			'Recovery 6mi',
			'8K - 15K tune - up race(total 9 - 13 mi / 14 - 21 km)',
			'Long run 18mi',
			'Recovery 6mi a.m. 4mi p.m.',
			'General aerobic 8mi',
			'VO₂ Max 12mi w / 6x1, 200 m @5K race pace; jog 50 to 90 % interval time between',
			'Medium - long run 15mi a.m.Recovery 4mi p.m.',
			'General aerobic + speed 8mi w / 8x100 m strides',
			'Recovery 6mi',
			'Long run 22mi',
			'Recovery 6mi',
			'VO₂ Max 9mi w / 5x600 m @5K race pace; jog 50 to 90 % interval time between',
			'Medium - long run 14mi',
			'Recovery + speed 7mi w / 6x100 m strides',
			'Recovery 6mi',
			'8K - 10K tune - up race(total 9 - 11 mi / 14 - 18 km)',
			'Long run 17mi',
			'Recovery 6mi',
			'General aerobic + speed 8mi w / 8x100 m strides',
			'Recovery 6mi',
			'VO₂ Max 9mi w / 3x1, 600 m @5K race pace; jog 50 to 90 % interval time between',
			'Recovery 5mi',
			'General aerobic + speed 7mi w / 8x100 m strides',
			'Medium - long run 13mi',
			'Recovery 6mi',
			'General aerobic 7mi',
			'Dress rehearsal 8mi w / 2mi @marathon race pace',
			'Recovery 6mi',
			'Recovery + speed 5mi w / 6x100 m strides',
			'Recovery 4mi',
			'Goal marathon 26.2mi',
		],
	},
	'Pfitzinger/Douglas: Up to 55 mi/wk - 12 weeks': {
		length: 12,
		name: 'Pfitzinger/Douglas: Up to 55 mi/wk, 12 weeks',
		workouts: [
			'Rest or cross-train',
			'General aerobic + speed 8mi w / 10x100m strides',
			'Rest or cross-train',
			'General aerobic 9mi',
			'Rest or cross-train',
			'Recovery 5mi',
			'Marathon pace run 13mi w / 8mi @marathon race pace',
			'Rest or cross-train',
			'Medium - long run 11mi',
			'Rest or cross-train',
			'Lactate threshold 8mi w 4mi @15K to half marathon race pace',
			'Rest or cross-train',
			'Recovery 5mi',
			'Medium - long run 15mi',
			'Rest or cross-train',
			'General aerobic + speed 8mi w / 10X100 m strides',
			'Recovery 4mi',
			'Medium - long run 11mi',
			'Rest or cross-train',
			'Recovery 4mi',
			'Marathon pace run 16mi w / 10mi @marathon race pace',
			'Rest or cross-train',
			'Recovery 5mi',
			'Lactate threshold 10mi w 5mi @15K to half marathon race pace',
			'Medium - long run 11mi',
			'Rest or cross-train',
			'Recovery 5mi',
			'Long run 17mi',
			'Rest or cross-train',
			'Rest or cross-train',
			'Medium - long run 12mi',
			'Rest or cross-train',
			'Lactate threshold 9mi w 4mi @15K to half marathon race pace',
			'Recovery 5mi',
			'Long run 16mi',
			'Rest or cross-train',
			'Recovery 5mi',
			'VO₂ Max 10mi w / 5x1000 m @5K race pace; jog 50 to 90 % interval time between',
			'Medium - long run 12mi',
			'Rest or cross-train',
			'Recovery + speed 6mi w / 6x100 m strides',
			'Marathon - pace run 15mi w / 12mi @marathon race pace',
			'Rest or cross-train',
			'Recovery + speed 6mi w / 6x100 m strides',
			'Medium - long run 12mi',
			'Rest or cross-train',
			'Lactate threshold 12mi w 7mi @15K to half marathon race pace',
			'Recovery 5mi',
			'Long run 20mi',
			'Rest or cross-train',
			'VO₂ Max 8mi w / 5x600 m @5K race pace; jog 50 to 90 % interval time between',
			'Medium - long run 11mi',
			'Rest or cross-train',
			'Recovery + speed 4mi w / 6x100 m strides',
			'8K - 15K tune - up race(total 9 - 13 mi / 14 - 21 km)',
			'Long run 17mi',
			'Rest or cross-train',
			'Recovery + speed 7mi w / 6x100 m strides',
			'VO₂ Max 10mi w / 4x1200 m @5K race pace; jog 50 to 90 % interval time between',
			'Rest or cross-train',
			'Medium - long run 11mi',
			'Recovery 4mi',
			'Long run 20mi',
			'Rest or cross-train',
			'VO₂ Max 8mi w / 5x600 m @5K race pace; jog 50 to 90 % interval time between',
			'Recovery 6mi',
			'Rest or cross-train',
			'Recovery + speed 4mi w / 6x100 m strides',
			'8K - 10K tune - up race(total 9 - 11 mi / 14 - 18 km)',
			'Long run 16mi',
			'Rest or cross-train',
			'General aerobic + speed 7mi w / 8x100 m strides',
			'VO₂ Max 8mi w / 3x1, 600 m @5K race pace; jog 50 to 90 % interval time between',
			'Rest or cross-train',
			'Recovery + speed 5mi w / 6x100 m strides',
			'Rest or cross-train',
			'Medium - long run 12mi',
			'Rest',
			'Recovery 6mi',
			'Dress rehearsal 7mi w / 2mi @marathon race pace',
			'Rest',
			'Recovery + speed 5mi w / 6x100 m strides',
			'Recovery 4mi',
			'Goal marathon 26.2mi',
		],
	},
	'Pfitzinger/Douglas: 55-70 mi/wk - 12 weeks': {
		length: 12,
		name: 'Pfitzinger/Douglas: 55-70 mi/wk, 12 weeks',
		workouts: [
			'Rest or cross-train',
			'General aerobic + speed 8mi w / 10x100m strides',
			'Medium - long run 11mi',
			'Recovery 5mi',
			'Medium - long run 11mi',
			'Recovery 5mi',
			'Marathon pace run 15mi w / 8mi @marathon race pace',
			'Rest or cross-train',
			'Medium - long run 12mi',
			'Medium - long run 11mi',
			'Recovery 5mi',
			'Lactate threshold 9mi w 4mi @15K to half marathon race pace',
			'Recovery 5mi',
			'Long run 17mi',
			'Rest or cross-train',
			'General aerobic + speed 8mi w / 10x100m strides',
			'Medium - long run 14mi',
			'Recovery 5mi',
			'Medium - long run 12mi',
			'Recovery 5mi',
			'Marathon pace run 17mi w / 10mi @marathon race pace',
			'Rest or cross-train',
			'Medium - long run 13mi',
			'Medium - long run 15mi',
			'Recovery 5mi',
			'Lactate threshold 10mi w 5mi @15K to half marathon race pace',
			'Recovery 5mi',
			'Long run 18mi',
			'Rest or cross-train',
			'General aerobic + speed 8mi w / 10x100m strides',
			'Medium - long run 15mi',
			'Recovery 5mi',
			'Lactate threshold 10mi w 4mi @15K to half marathon race pace',
			'General aerobic 7mi',
			'Long run 17mi',
			'Rest or cross-train',
			'Recovery 6mi a.m. 4mi p.m.',
			'VO₂ Max 11mi w / 5x1200 m @5K race pace; jog 50 to 90 % interval time between',
			'Medium - long run 15mi',
			'General aerobic 10mi',
			'Recovery 6mi',
			'Marathon - pace run 18mi w / 12mi @marathon race pace',
			'Rest or cross-train',
			'General aerobic + speed 9mi w / 10x100m strides',
			'Medium - long run 15mi',
			'Recovery 7mi',
			'Lactate threshold 12mi w 7mi @15K to half marathon race pace',
			'Recovery 6mi',
			'Long run 21mi',
			'Rest or cross-train',
			'VO₂ Max 9mi w / 5x600 m @5K race pace; jog 50 to 90 % interval time between',
			'Medium - long run 15mi',
			'Recovery + speed 7mi w / 6x100 m strides',
			'Recovery 6mi',
			'8K - 15K tune - up race(total 9 - 13 mi / 14 - 21 km)',
			'Long run 18mi',
			'Rest or cross-train',
			'Recovery 6mi a.m. 4mi p.m.',
			'VO₂ Max 11mi w / 6x1, 000 m @5K race pace; jog 50 to 90 % interval time between',
			'Medium - long run 15mi',
			'General aerobic 8mi',
			'Recovery 6mi',
			'Long run 20mi',
			'Rest or cross-train',
			'VO₂ Max 8mi w / 5x600 m @5K race pace; jog 50 to 90 % interval time between',
			'Medium - long run 12mi',
			'Recovery + speed 6mi w / 6x100 m strides',
			'Recovery 5mi',
			'8K - 10K tune - up race(total 9 - 13 mi / 14 - 21 km)',
			'Long run 17mi',
			'Rest or cross-train',
			'General aerobic + speed 8mi w / 10x100m strides',
			'Recovery 4mi',
			'VO₂ Max 8mi w / 3x1, 600 m @5K race pace; jog 50 to 90 % interval time between',
			'Recovery 5mi',
			'Recovery + speed 6mi w / 10x100 m strides',
			'Medium - long run 13mi',
			'Rest',
			'Recovery 7mi',
			'Dress rehearsal 7mi w / 2mi @marathon race pace',
			'Recovery 5mi',
			'Recovery + speed 5mi w / 6x100 m strides',
			'Recovery 4mi',
			'Goal marathon 26.2mi',
		],
	},
	'JenReviews - 26 weeks': {
		length: 26,
		name: 'JenReviews, 6 months',
		workouts: [
			'2 mi',
			'rest',
			'2mi',
			'rest',
			'2mi',
			'rest',
			'rest',
			'3mi',
			'rest',
			'fartlek - 20m',
			'rest',
			'2mi',
			'rest',
			'3mi',
			'rest',
			'3mi',
			'fartlek - 20m',
			'rest',
			'3mi',
			'rest',
			'4mi',
			'recovery',
			'rest',
			'3mi',
			'cross - 30m',
			'3mi',
			'rest',
			'5mi',
			'recovery',
			'rest',
			'3mi',
			'fartlek - 20m',
			'3mi',
			'rest',
			'6mi',
			'recovery',
			'rest',
			'3mi',
			'fartlek - 30m',
			'3mi',
			'rest',
			'7mi',
			'recovery',
			'rest',
			'3mi',
			'cross - 30m',
			'2mi',
			'rest',
			'5mi',
			'recovery',
			'rest',
			'2mi',
			'fartlek - 30m',
			'3mi',
			'rest',
			'8mi',
			'recovery',
			'rest',
			'3mi',
			'fartlek - 30m',
			'3mi',
			'rest',
			'9mi',
			'recovery',
			'rest',
			'3mi',
			'cross - 30m',
			'3mi',
			'rest',
			'6mi',
			'recovery',
			'rest',
			'3mi',
			'fartlek - 30m',
			'3mi',
			'rest',
			'10mi',
			'recovery',
			'rest',
			'3mi',
			'fartlek - 30m',
			'4mi',
			'rest',
			'11mi',
			'recovery',
			'rest',
			'3mi',
			'cross - 30m',
			'3mi',
			'rest',
			'8mi',
			'recovery',
			'rest',
			'3mi',
			'fartlek - 30m',
			'4mi',
			'rest',
			'12mi',
			'recovery',
			'rest',
			'3mi',
			'fartlek - 45m',
			'4mi',
			'rest',
			'14mi',
			'recovery',
			'rest',
			'3mi',
			'cross - 30m',
			'3mi',
			'rest',
			'6mi',
			'recovery',
			'rest',
			'2mi',
			'fartlek - 30m',
			'4mi',
			'rest',
			'16mi',
			'recovery',
			'rest',
			'4mi',
			'fartlek - 45m',
			'5mi',
			'rest',
			'10mi',
			'recovery',
			'rest',
			'4mi',
			'fartlek - 30m',
			'4mi',
			'rest',
			'18mi',
			'recovery',
			'rest',
			'4mi',
			'cross - 30m',
			'5mi',
			'rest',
			'8mi',
			'recovery',
			'rest',
			'5mi',
			'fartlek - 45m',
			'5mi',
			'rest',
			'10mi',
			'recovery',
			'rest',
			'5mi',
			'fartlek - 45m',
			'4mi',
			'rest',
			'20mi',
			'recovery',
			'rest',
			'5mi',
			'cross - 30m',
			'5mi',
			'rest',
			'10mi',
			'recovery',
			'rest',
			'5mi',
			'farlek - 45m',
			'4mi',
			'rest',
			'8mi',
			'recovery',
			'rest',
			'4mi',
			'farlek - 30m',
			'3mi',
			'rest',
			'6mi',
			'recovery',
			'3mi',
			'rest',
			'2mi',
			'rest',
			'rest',
			'race',
		],
	},
	'Hansons Beginner Half Marathon - 18 weeks': {
		length: 18,
		name: 'Hansons Beginner Half Marathon',
		workouts: [
			'Rest or cross-train',
			'Rest or cross-train',
			'Rest or cross-train',
			'easy 3mi',
			'Rest or cross-train',
			'easy 3mi',
			'easy 4mi',
			'Rest or cross-train',
			'easy 2mi',
			'Rest or cross-train',
			'easy 3mi',
			'easy 3mi',
			'easy 3mi',
			'easy 4mi',
			'Rest or cross-train',
			'easy 4mi',
			'Rest or cross-train',
			'easy 4mi',
			'easy 4mi',
			'easy 4mi',
			'easy 5mi',
			'Rest or cross-train',
			'easy 5mi',
			'Rest or cross-train',
			'easy 3mi',
			'easy 3mi',
			'easy 5mi',
			'easy 6mi',
			'Rest or cross-train',
			'easy 5mi',
			'Rest or cross-train',
			'2mi warm up 3mi @HMP 2mi cool down',
			'easy 5mi',
			'easy 4mi',
			'8mi long run',
			'easy 4mi',
			'2mi warm up 12x400m @5k - 10k pace w. 400m jog rest 2mi cool down',
			'Rest or cross-train',
			'2mi warm up 3mi@HMP 2mi cool down',
			'easy 4mi',
			'easy 5mi',
			'9mi long run',
			'easy 4mi',
			'2mi warm up 8x600m @5k - 10k pace w. 400m jog rest 2mi cool down',
			'Rest or cross-train',
			'2mi warm up 3mi@HMP 2mi cool down',
			'easy 4mi',
			'easy 6mi',
			'10mi long run',
			'easy 6mi',
			'2mi warm up 6x800m @5k - 10k pace w. 400m jog rest 2mi cool down',
			'Rest or cross-train',
			'2mi warm up 4mi@HMP 2mi cool down',
			'easy 5mi',
			'easy 6mi',
			'10mi long run',
			'easy 5mi',
			'2mi warm up 5x1k @5k - 10k pace w. 600m jog rest 2mi cool down',
			'Rest or cross-train',
			'2mi warm up 4mi@HMP 2mi cool down',
			'easy 6mi',
			'easy 5mi',
			'10mi long run',
			'easy 6mi',
			'2mi warm up 4x1200m @5k - 10k pace w. 600m jog rest 2mi cool down',
			'Rest or cross-train',
			'2mi warm up 4mi@HMP 2mi cool down',
			'easy 5mi',
			'easy 5mi',
			'12mi long run',
			'easy 5mi',
			'2mi warm up 6x1mi @HMP -10s w. 400m jog rest 2mi cool down',
			'Rest or cross-train',
			'2mi warm up 5mi@HMP 2mi cool down',
			'easy 6mi',
			'easy 5mi',
			'10mi long run',
			'easy 5mi',
			'2mi warm up 4x2mi @HMP -10s w. 800m jog rest 2mi cool down',
			'Rest or cross-train',
			'2mi warm up 5mi@HMP 2mi cool down',
			'easy 5mi',
			'easy 6mi',
			'12mi long run',
			'easy 6mi',
			'2mi warm up 3x2mi @HMP -10s w. 800m jog rest 2mi cool down',
			'Rest or cross-train',
			'2mi warm up 5mi@HMP 2mi cool down',
			'easy 6mi',
			'easy 5mi',
			'10mi long run',
			'easy 5mi',
			'2mi warm up 2x3mi @HMP -10s w. 1mi jog rest 2mi cool down',
			'Rest or cross-train',
			'2mi warm up 6mi@HMP 2mi cool down',
			'easy 5mi',
			'easy 6mi',
			'12mi long run',
			'easy 7mi',
			'2mi warm up 3x2mi @HMP -10s w. 800m jog rest 2mi cool down',
			'Rest or cross-train',
			'2mi warm up 6mi@HMP 2mi cool down',
			'easy 6mi',
			'easy 5mi',
			'10mi long run',
			'easy 5mi',
			'2mi warm up 4x2mi @HMP -10s w. 800m jog rest 2mi cool down',
			'Rest or cross-train',
			'2mi warm up 6mi@HMP 2mi cool down',
			'easy 5mi',
			'easy 6mi',
			'12mi long run',
			'easy 5mi',
			'2mi warm up 6x1mi @HMP -10s w. 400m jog rest 2mi cool down',
			'Rest or cross-train',
			'2mi warm up 5mi@HMP 2mi cool down',
			'easy 6mi',
			'easy 5mi',
			'easy 8mi',
			'easy 5mi',
			'easy 5mi',
			'Rest or cross-train',
			'easy 6mi',
			'easy 5mi',
			'easy 3mi',
			'Race Day!',
		],
	},
	'Hansons Advanced Half Marathon - 18 weeks': {
		length: 18,
		name: 'Hansons Advanced Half Marathon',
		workouts: [
			'Rest or Cross - Train',
			'Rest or Cross - Train',
			'Rest or Cross - Train',
			'4mi easy',
			'3mi easy',
			'4mi easy',
			'6mi easy',
			'4mi easy',
			'2mi warm up 12x400m @5k - 10k pace w. 400m jog rest 2mi cool down',
			'Rest or Cross - Train',
			'2mi warm up 3mi@HMP 2mi cool down',
			'4mi easy',
			'4mi easy',
			'6mi easy',
			'4mi easy',
			'2mi warm up 8x600m @5k - 10k pace w. 400m jog rest 2mi cool down',
			'Rest or Cross - Train',
			'2mi warm up 3mi@HMP 2mi cool down',
			'5mi easy',
			'5mi easy',
			'7mi easy',
			'5mieasy',
			'2mi warm up 6x800m @5k - 10k pace w. 400m jog rest 2mi cool down',
			'Rest or Cross - Train',
			'2mi warm up 3mi@HMP 2mi cool down',
			'4mi easy 5',
			'6mi easy 5',
			'8mi easy 5',
			'4mi easy',
			'2mi warm up 5x1k @5k - 10k pace w. 600m jog rest 2mi cool down',
			'Rest or Cross - Train',
			'2mi warm up 4mi@HMP 2mi cool down',
			'5mi easy',
			'6mi easy',
			'10mi long run',
			'5mi easy',
			'2mi warm up 4x1200m @5k - 10k pace w. 600m jog rest 2mi cool down',
			'Rest or Cross - Train',
			'2mi warm up 4mi@HMP 2mi cool down',
			'6mi easy 6',
			'6mi easy 6',
			'12mi long run',
			'5mi easy',
			'2mi warm up 3x1mi @5k - 10k pace w. 800m jog rest 2mi cool down',
			'Rest or Cross - Train',
			'2mi warm up 4mi@HMP 2mi cool down',
			'6mieasy',
			'5mieasy',
			'10mi long run',
			'6mi easy',
			'2mi warm up 5x1k @5k - 10k pace w. 600m jog rest 2mi cool down',
			'Rest or Cross - Train',
			'2mi warm up 5mi@HMP 2mi cool down',
			'6mi easy',
			'6mi easy',
			'12mi long run',
			'5mi easy',
			'2mi warm up 6x800m @5k - 10k pace w. 400m jog rest 2mi cool down',
			'Rest or Cross - Train',
			'2mi warm up 5mi@HMP 2mi cool down',
			'6mi easy',
			'5mi easy',
			'10mi long run',
			'7mi easy',
			'2mi warm up 12x400m @5k - 10k pace w. 400m jog rest 2mi cool down',
			'Rest or Cross - Train',
			'2mi warm up 5mi@HMP 2mi cool down',
			'5mi easy',
			'6mi easy',
			'12mi long run',
			'5mi easy',
			'2mi warm up 6x1mi @10k pace w. 400m jog rest 2mi cool down',
			'Rest or Cross - Train',
			'2mi warm up 6mi@HMP 2mi cool down',
			'6mi easy',
			'5mi easy',
			'10mi long run',
			'5mi easy',
			'2mi warm up 4x2mi @10k pace w. 800m jog rest 2mi cool down',
			'Rest or Cross - Train',
			'2mi warm up 6mi@HMP 2mi cool down',
			'5mi easy',
			'6mi easy',
			'14mi long run',
			'7mi easy',
			'2mi warm up 3x2mi @10k pace w. 800m jog rest 2mi cool down',
			'Rest or Cross - Train',
			'2mi warm up 6mi@HMP 2mi cool down',
			'6mi easy',
			'5mi easy',
			'10mi long run',
			'5mi easy',
			'2mi warm up 2x3mi @10k pace w. 1mi jog rest 2mi cool down',
			'Rest or Cross - Train',
			'2mi warm up 7mi@HMP 2mi cool down',
			'5mi easy',
			'6mi easy',
			'14mi long run',
			'7mi easy',
			'2mi warm up 3x2mi @10k pace w. 800m jog rest 2mi cool down',
			'Rest or Cross - Train',
			'2mi warm up 7mi@HMP 2mi cool down',
			'6mi easy',
			'5mi easy',
			'10mi long run',
			'5mi easy',
			'2mi warm up 4x2mi @10k pace w. 800m jog rest 2mi cool down',
			'Rest or Cross - Train',
			'2mi warm up 7mi@HMP 2mi cool down',
			'5mi easy',
			'6mi easy',
			'14mi long run',
			'7mi easy',
			'2mi warm up 6x1mi @10k pace w. 400m jog rest 2mi cool down',
			'Rest or Cross - Train',
			'2mi warm up 5mi@HMP 2mi cool down',
			'6mi easy',
			'5mi easy',
			'8mi easy',
			'5mi easy',
			'5mi easy',
			'Rest or Cross - Train',
			'6mi easy',
			'5mi easy',
			'3mi Shakeout Run',
			'Race Day!',
		],
	},
};
